language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
    - TESTFOLDER=tutorials/unit-tests
    - TESTFOLDER=tutorials/street/version-1/pedestrian
    - TESTFOLDER=tutorials/street/version-1/street
    - TESTFOLDER=tutorials/street/version-1/integration-tests
script: "jest $TESTFOLDER"
